language: node_js

sudo: false

node_js:
  - '4.2.2'
  - '6'

before_install:
  - npm install -g npm@3

install:
  - npm install && npm run lint_src

cache:
  directories:
    - node_modules

services:
  - redis-server

after_success:
  - npm run cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js