language: node_js

sudo: false

node_js:
  - '8'

install:
  - npm install && npm run lint

cache:
  directories:
    - node_modules

services:
  - redis-server

after_success:
  - npm run cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js